{
  "comments": [
    {
      "key": {
        "uuid": "ef0768fc_e0740e5f",
        "filename": "org.eclipse.egit.core/src/org/eclipse/egit/core/op/PullOperation.java",
        "patchSetId": 7
      },
      "lineNbr": 186,
      "author": {
        "id": 44628
      },
      "writtenOn": "2018-11-03T09:16:17Z",
      "side": 1,
      "message": "This indicates not a cancellation but that this thread was interrupted. (Per javadoc on JobGroup.join.)\n\nIf you can\u0027t let the exception propagate you should at least re-set the interrupted flag.\n\nSo I think this should be\n\n  try {\n    jobGroup.join(noTimeout, progress);\n  } catch (InterruptedException e) {\n    Thread.currentThread().interrupt();\n    throw new CoreException(Status.CANCEL_STATUS);\n  } catch (OperationCanceledException e) {\n    throw new CoreException(Status.CANCEL_STATUS);\n  }\n\nSee https://www.ibm.com/developerworks/library/j-jtp05236/index.html .",
      "range": {
        "startLine": 186,
        "startChar": 40,
        "endLine": 186,
        "endChar": 60
      },
      "revId": "c17af627202345e80545abe791c374e74854991d",
      "serverId": "97ee7c02-f12f-4043-b43e-dea463d88b31",
      "unresolved": false
    }
  ]
}